name: EKS Provisioning

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  CLUSTER_NAME: eks-creation

jobs:
  provision:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050451391072:role/GitHubActionsEKSDeployRole # Replace with your IAM Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Initialize Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Validate Terraform
        working-directory: ./terraform
        run: terraform validate

      - name: Apply Terraform
        working-directory: ./terraform
        run: terraform apply -auto-approve

  deploy:
    runs-on: ubuntu-latest
    needs: provision

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::050451391072:role/GitHubActionsEKSDeployRole # Replace with your IAM Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        run: |
         curl -LO "https://dl.k8s.io/release/v1.30.4/bin/linux/amd64/kubectl"
         chmod +x kubectl && sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy ConfigMap
        run: kubectl apply -f kubernetes/html-configmap.yaml

      - name: Deploy App
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
